version: '3'
services:
    learnblog:
        ports:
            - "8080:8080"
        image: "learnblog"
        links:
            - database
        env_file:
            - env/dev/learnblog.env
        networks:
            - learnblog-network
    database:
        ports:
            - "5432:5432"
        image: "postgres:14-alpine"
        volumes:
          - db-volume:/var/lib/postgresql
        env_file:
            - env/dev/postgres.env
        networks:
            - learnblog-network
volumes:
  db-volume:
networks:
    learnblog-network: